FROM node:22

# ARGs
ARG NODE_ENV=production
ARG MIDTRANS_CLIENT_KEY
ARG MIDTRANS_SNAP_SCRIPT
ARG NEXT_PUBLIC_API_URL

# ENVs
ENV NODE_ENV=$NODE_ENV
ENV MIDTRANS_CLIENT_KEY=$MIDTRANS_CLIENT_KEY
ENV MIDTRANS_SNAP_SCRIPT=$MIDTRANS_SNAP_SCRIPT
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL

WORKDIR /app

COPY . /app

RUN npm install

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]
